# SITE CONFIGURATION
baseurl: ""
url: "http://dutraneto.com"
image-url: bf2ef3d1ef81116084d366b284184f3a

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  site_name: "The Dude Developer"
  title: "The Dude Developer"
  #avatar: assets/img/avatar.png
  favicon: assets/favicon-96x96.png
  gravatar: bf2ef3d1ef81116084d366b284184f3a
  description: "A website approaching python and technologies"
    

  # Header and footer text
  header_text: >
    <p>This website was developed to study programming languages, teaching and aproaching new features and technologies related to IT.</p>
    <p>Welcome all of you and feel free to give a feedback.</p>
  header_text_feature_image:
  # footer_text: >
  
  # Icons
  rss: false
  email_address: # "dutraneto@me.com"
  behance:
  bitbucket:
  dribbble:
  facebook: # "dudutraneto"
  flickr:
  gitlab:
  github: "dutraneto"
  google_plus:
  instagram:
  linkedin: "https://www.linkedin.com/in/jos%C3%A9-neto-656842147/"
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter:  # "Dutranetom"
  wordpress:
  youtube:

  # SVG Icons
  svg-icon:
    python: true
    javascript: true
    node: true

  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname: "the-dude-developer"
  katex: true # Enable if using math markup
  search: false # Enable the search feature

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_continue_reading: "Continue reading"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."
  str_search_no_results: "No results found."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: true

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
permalink: /:title
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate]
theme:
exclude:
  - Gemfile
  - Gemfile.lock
